apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eosc-noise-5gb
  namespace: crons
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        role: eosc-crons-env
    spec:
      template:
        metadata:
          labels:
            role: eosc-crons-env
        spec:
          containers:
          - name: eosc-noise-5gb
            image: projectescape/eosc-crons:stable
            tty: true
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - date; echo Hello from EOSC-NOISE; echo "Generating Rucio CFG"; j2 home/user/eosc-crons/rucio.cfg.escape.j2 | sed '/^\s*$/d' > /opt/rucio/etc/rucio.cfg; FILE_SIZE=5G /bin/bash /home/user/eosc-crons/noise/rucio_produce_noise.sh
            resources:
              requests:
                memory: 1Gi
                ephemeral-storage: 6Gi
              limits:
                memory: 2Gi
                ephemeral-storage: 6Gi
          restartPolicy: OnFailure
